<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <UseWindowsForms>true</UseWindowsForms>
    <EnableWindowsTargeting>true</EnableWindowsTargeting>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <AssemblyName>Agente-Big-Lanche</AssemblyName>
    <RootNamespace>BigLancheAgentLauncher</RootNamespace>
  </PropertyGroup>
  <ItemGroup>
    <EmbeddedResource Include="BigLanchePrinter.ps1" />
  </ItemGroup>
</Project>